# Generated by Django 5.1.4 on 2026-05-08 23:50

import django.core.validators
import django.db.models.deletion
import inscription.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('commune_residence', models.CharField(max_length=120)),
                ('etablissement', models.CharField(max_length=255)),
                ('classe_niveau', models.CharField(choices=[('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('AUTRE', 'Autre')], max_length=10)),
                ('filiere', models.CharField(max_length=120)),
                ('motivation_texte', models.TextField(blank=True)),
                ('numero_dossier', models.CharField(blank=True, max_length=32, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_inscription',),
            },
        ),
        migrations.CreateModel(
            name='Consentement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_donnees_personnelles', models.BooleanField(default=False)),
                ('consent_reglement', models.BooleanField(default=False)),
                ('consent_selection', models.BooleanField(default=False)),
                ('consent_photos_videos', models.BooleanField(default=False)),
                ('consent_autorisation_parentale_declaree', models.BooleanField(default=False)),
                ('consent_engagement_presence', models.BooleanField(default=False)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentement', to='inscription.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_identite', models.FileField(upload_to='documents/pieces/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('bulletin_an1', models.FileField(upload_to='documents/bulletins/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('bulletin_an2', models.FileField(upload_to='documents/bulletins/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('lettre_motivation', models.FileField(upload_to='documents/motivation/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('lettre_recommandation', models.FileField(blank=True, upload_to='documents/recommandation/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('autorisation_parentale', models.FileField(blank=True, upload_to='documents/autorisation/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inscription.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='NotesAcademiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale_an1', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_generale_an2', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_maths_an1', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_maths_an2', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_physique_an1', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_physique_an2', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('appreciation_generale', models.TextField(blank=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inscription.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('electronique', 'Électronique'), ('mathematiques', 'Mathématiques'), ('informatique', 'Informatique'), ('ia', 'Intelligence Artificielle'), ('entrepreneuriat', 'Entrepreneuriat'), ('divers', 'Divers / Culture Tech')], max_length=32)),
                ('ordre', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('bonne_reponse', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
            options={
                'ordering': ('categorie', 'ordre'),
                'unique_together': {('categorie', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='QuizReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_electronique', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_mathematiques', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_informatique', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_ia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_entrepreneuriat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_divers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('reponses_json', models.JSONField(blank=True, default=dict)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='inscription.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='StatutCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RETENU', 'Retenu'), ('LISTE_ATTENTE', "Liste d'attente"), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('commentaire_jury', models.TextField(blank=True)),
                ('note_motivation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('date_decision', models.DateTimeField(auto_now=True)),
                ('score_global_selection', models.FloatField(default=0.0)),
                ('email_envoye', models.BooleanField(default=False)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='inscription.candidat')),
            ],
        ),
    ]
