# Generated by Django 5.1.4 on 2026-05-09 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='motivation_texte',
        ),
    ]
