# Generated by Django 5.1.4 on 2026-05-09 15:09

import django.core.validators
import inscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_remove_candidat_motivation_texte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesacademiques',
            name='appreciation_generale',
        ),
        migrations.AddField(
            model_name='documents',
            name='attestation_diplome',
            field=models.FileField(blank=True, upload_to='documents/diplomes/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='documents',
            name='dernier_releve_notes',
            field=models.FileField(blank=True, upload_to='documents/releves/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='notesacademiques',
            name='diplome_plus_eleve',
            field=models.CharField(blank=True, choices=[('CEP', 'CEP'), ('BEPC', 'BEPC'), ('CAP', 'CAP'), ('DTI', 'DTI'), ('BAC', 'BAC'), ('DUT', 'DUT'), ('LICENCE', 'LICENCE'), ('MASTER', 'MASTER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='classe_niveau',
            field=models.CharField(choices=[('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('AUTRE', 'Professionnel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='documents',
            name='bulletin_an1',
            field=models.FileField(blank=True, upload_to='documents/bulletins/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='bulletin_an2',
            field=models.FileField(blank=True, upload_to='documents/bulletins/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='notesacademiques',
            name='moyenne_generale_an1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='notesacademiques',
            name='moyenne_generale_an2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='notesacademiques',
            name='moyenne_maths_an1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='notesacademiques',
            name='moyenne_maths_an2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='notesacademiques',
            name='moyenne_physique_an1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='notesacademiques',
            name='moyenne_physique_an2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
