# Generated by Django 5.1.4 on 2026-05-10 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_remove_notesacademiques_appreciation_generale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizreponse',
            old_name='score_electronique',
            new_name='score_physique',
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_physique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='categorie',
            field=models.CharField(choices=[('physique', 'Physique'), ('mathematiques', 'Mathématiques'), ('informatique', 'Informatique'), ('ia', 'Intelligence Artificielle'), ('entrepreneuriat', 'Entrepreneuriat'), ('divers', 'Divers / Culture Tech')], max_length=32),
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_divers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_entrepreneuriat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_ia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_informatique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_mathematiques',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quizreponse',
            name='score_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]

