# Generated by Django 5.1.4 on 2026-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_remove_quizreponse_score_electronique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizreponse',
            name='quiz_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
