# Generated by Django 5.1.4 on 2026-05-12 01:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inscription.models
from django.db import migrations, models


def seed_default_challenges(apps, schema_editor):
    Challenge = apps.get_model("inscription", "Challenge")
    ChallengePortalSettings = apps.get_model("inscription", "ChallengePortalSettings")
    defaults_map = {
        3: "Challenge 1 - Jour 3 : Installation Arduino IDE & Arduino UNO",
        4: "Challenge 2 - Jour 4 : LED, PWM et bases pratiques Arduino",
        5: "Challenge 3 - Jour 5 : Mini-projet 1 & capteurs environnementaux",
        6: "Challenge 4 - Jour 6 : Mini-projet 2 & capteurs (approche projet)",
        7: "Challenge 5 - Jour 7 : Buzzer, Tilt et logique d'evenements",
        8: "Challenge 6 - Jour 8 : Boutons, RFID et servo-moteur",
        9: "Challenge 7 - Jour 9 : Shift register, servo et orchestration",
        10: "Challenge 8 - Jour 10 : Mini-projet LCD & microcontroleurs alternatifs",
    }
    for day in range(3, 11):
        Challenge.objects.get_or_create(
            sequence_day=day,
            defaults={
                "title": defaults_map[day],
                "description": "Module challenge AFTEC (QCM / pratique) pour la sequence du jour.",
            },
        )
    ChallengePortalSettings.objects.get_or_create(id=1, defaults={"is_enabled": False})


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_quizreponse_quiz_elapsed_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_day', models.PositiveSmallIntegerField(choices=[(3, 'Jour 3'), (4, 'Jour 4'), (5, 'Jour 5'), (6, 'Jour 6'), (7, 'Jour 7'), (8, 'Jour 8'), (9, 'Jour 9'), (10, 'Jour 10')], unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('challenge_pdf', models.FileField(blank=True, upload_to='challenges/pdfs/', validators=[inscription.models.validate_pdf_extension, inscription.models.validate_file_size])),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ('sequence_day',),
            },
        ),
        migrations.CreateModel(
            name='ChallengePortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametre challenges',
                'verbose_name_plural': 'Parametres challenges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_file', models.FileField(blank=True, upload_to='challenges/reponses/', validators=[inscription.models.validate_file_extension, inscription.models.validate_file_size])),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('jury_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to='inscription.candidat')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='inscription.challenge')),
            ],
            options={
                'verbose_name': 'Soumission challenge',
                'verbose_name_plural': 'Soumissions challenges',
                'ordering': ('challenge__sequence_day', 'elapsed_seconds'),
                'unique_together': {('challenge', 'candidat')},
            },
        ),
        migrations.RunPython(seed_default_challenges, migrations.RunPython.noop),
    ]
