# Generated by Django 5.1.4 on 2026-05-12 02:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from inscription.challenges_data import CHALLENGE_QCM_DATA


def seed_challenge_questions(apps, schema_editor):
    Challenge = apps.get_model("inscription", "Challenge")
    ChallengeQuestion = apps.get_model("inscription", "ChallengeQuestion")
    for payload in CHALLENGE_QCM_DATA:
        challenge, _ = Challenge.objects.get_or_create(
            sequence_day=payload["sequence_day"],
            defaults={
                "title": payload["title"],
                "description": payload.get("description", ""),
            },
        )
        if challenge.title != payload["title"] or challenge.description != payload.get("description", ""):
            challenge.title = payload["title"]
            challenge.description = payload.get("description", "")
            challenge.save(update_fields=["title", "description", "updated_at"])

        seen_orders = []
        for order, question_data in enumerate(payload.get("questions", []), start=1):
            ChallengeQuestion.objects.update_or_create(
                challenge=challenge,
                order=order,
                defaults={
                    "question": question_data["question"],
                    "option_a": question_data["option_a"],
                    "option_b": question_data["option_b"],
                    "option_c": question_data["option_c"],
                    "option_d": question_data["option_d"],
                    "correct_option": question_data["correct"],
                },
            )
            seen_orders.append(order)
        if seen_orders:
            ChallengeQuestion.objects.filter(challenge=challenge).exclude(order__in=seen_orders).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_challenge_challengeportalsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_pdf',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='answer_file',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='answers_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inscription.challenge')),
            ],
            options={
                'verbose_name': 'Question challenge',
                'verbose_name_plural': 'Questions challenges',
                'ordering': ('order',),
                'unique_together': {('challenge', 'order')},
            },
        ),
        migrations.RunPython(seed_challenge_questions, migrations.RunPython.noop),
    ]
