# Generated by Django 5.1.4 on 2026-05-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_remove_challenge_challenge_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='bulletin_an1',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='bulletin_an2',
        ),
    ]
