# Generated by Django 5.1.4 on 2026-05-22 07:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_remove_documents_bulletin_an1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidat',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), django.db.models.functions.text.Lower('prenom'), name='uniq_candidat_nom_prenom_ci'),
        ),
    ]
