# Auto-generated from Challenges.docx
CHALLENGE_QCM_DATA = [{'sequence_day': 3,
  'title': 'Challenge 1 — Jour 3 : Installation Arduino IDE & Prise en main Arduino UNO',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'Quel logiciel permet de programmer une carte Arduino ?',
                 'option_a': 'Photoshop',
                 'option_b': 'Arduino IDE',
                 'option_c': 'VLC',
                 'option_d': 'GitHub',
                 'correct': 'B'},
                {'question': 'Quel bouton permet d’envoyer le programme vers la carte ?',
                 'option_a': 'Vérifier',
                 'option_b': 'Debug',
                 'option_c': 'Transférer',
                 'option_d': 'Compiler',
                 'correct': 'C'},
                {'question': 'Dans Arduino, quelle fonction s’exécute en boucle ?',
                 'option_a': 'start()',
                 'option_b': 'main()',
                 'option_c': 'setup()',
                 'option_d': 'loop()',
                 'correct': 'D'},
                {'question': 'Quel pin est utilisé par la LED intégrée dans Blink ?',
                 'option_a': '2',
                 'option_b': '7',
                 'option_c': '13',
                 'option_d': 'A0',
                 'correct': 'C'},
                {'question': 'delay(1000) correspond à :',
                 'option_a': '100 secondes',
                 'option_b': '10 secondes',
                 'option_c': '1 seconde',
                 'option_d': '0.1 seconde',
                 'correct': 'C'},
                {'question': 'Le bouton « Vérifier » dans l’IDE permet de :',
                 'option_a': 'Téléverser le code',
                 'option_b': 'Déboguer le programme',
                 'option_c': 'Vérifier les erreurs de syntaxe',
                 'option_d': 'Ouvrir le moniteur série',
                 'correct': 'C'},
                {'question': 'Où trouve-t-on les exemples officiels dans l’IDE Arduino ?',
                 'option_a': 'Menu Outils',
                 'option_b': 'Fichier → Exemples',
                 'option_c': 'Croquis → Ajouter',
                 'option_d': 'Aide',
                 'correct': 'B'},
                {'question': 'La carte Arduino Uno est basée sur quel microcontrôleur ?',
                 'option_a': 'ESP32',
                 'option_b': 'ATmega328P',
                 'option_c': 'STM32',
                 'option_d': 'Raspberry Pi',
                 'correct': 'B'},
                {'question': 'Que signifie « FQBN » dans arduino-cli ou l’IDE ?',
                 'option_a': 'Fully Qualified Board Name',
                 'option_b': 'Fast Quick Board Navigation',
                 'option_c': 'File Quality Binary Number',
                 'option_d': 'Flash Quick Bootloader Name',
                 'correct': 'A'},
                {'question': 'Le moniteur série permet de :',
                 'option_a': 'Compiler le code',
                 'option_b': 'Voir les messages Serial.print()',
                 'option_c': 'Alimenter la carte',
                 'option_d': 'Téléverser sans câble',
                 'correct': 'B'}]},
 {'sequence_day': 4,
  'title': 'Challenge 2 — Jour 4 : Les bases de l’Arduino et les sorties simples (LEDs)',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'Pourquoi utilise-t-on une résistance avec une LED ?',
                 'option_a': 'Pour augmenter la tension',
                 'option_b': 'Pour protéger la LED',
                 'option_c': 'Pour refroidir Arduino',
                 'option_d': 'Pour stocker l’énergie',
                 'correct': 'B'},
                {'question': 'Quelle résistance donnera la LED la plus brillante ?',
                 'option_a': '10kΩ',
                 'option_b': '1kΩ',
                 'option_c': '220Ω',
                 'option_d': '1MΩ',
                 'correct': 'C'},
                {'question': 'La patte longue d’une LED correspond :',
                 'option_a': 'Au négatif',
                 'option_b': 'Au positif',
                 'option_c': 'À la masse',
                 'option_d': 'Au signal',
                 'correct': 'B'},
                {'question': 'analogWrite() permet de :',
                 'option_a': 'Lire une valeur analogique',
                 'option_b': 'Créer un signal PWM',
                 'option_c': 'Activer uniquement le mode digital',
                 'option_d': 'Mesurer une tension',
                 'correct': 'B'},
                {'question': 'La fonction pinMode(13, OUTPUT) sert à :',
                 'option_a': 'Configurer la broche 13 en sortie',
                 'option_b': 'Lire l’état de la broche 13',
                 'option_c': 'Activer la résistance de pull-up',
                 'option_d': 'Configurer la broche en entrée',
                 'correct': 'A'},
                {'question': 'digitalWrite(13, HIGH) correspond à :',
                 'option_a': '0V',
                 'option_b': '5V (ou 3.3V)',
                 'option_c': 'PWM',
                 'option_d': 'Entrée',
                 'correct': 'B'},
                {'question': 'Combien de broches PWM natives possède l’Arduino Uno ?',
                 'option_a': '3',
                 'option_b': '6',
                 'option_c': '8',
                 'option_d': '14',
                 'correct': 'B'},
                {'question': 'Une breadboard permet :',
                 'option_a': 'De programmer Arduino',
                 'option_b': 'De faire des montages sans soudure',
                 'option_c': 'D’alimenter un moteur',
                 'option_d': 'D’envoyer Internet',
                 'correct': 'B'},
                {'question': 'Une LED RGB contient :',
                 'option_a': '2 LEDs',
                 'option_b': '3 LEDs',
                 'option_c': '5 LEDs',
                 'option_d': '1 moteur',
                 'correct': 'B'},
                {'question': 'La fonction map() sert à :',
                 'option_a': 'Changer l’échelle d’une valeur',
                 'option_b': 'Créer une carte',
                 'option_c': 'Mesurer la distance',
                 'option_d': 'Afficher du texte',
                 'correct': 'A'}]},
 {'sequence_day': 5,
  'title': 'Challenge 3 — Jour 5 : Mini-projet 1 & Capteurs environnementaux (début)',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'Une photorésistance réagit :',
                 'option_a': 'Au son',
                 'option_b': 'À la chaleur',
                 'option_c': 'À la lumière',
                 'option_d': 'Au mouvement',
                 'correct': 'C'},
                {'question': 'Le DHT11 mesure :',
                 'option_a': 'Distance',
                 'option_b': 'Température et humidité',
                 'option_c': 'Gaz',
                 'option_d': 'Pression',
                 'correct': 'B'},
                {'question': 'Le capteur de niveau d’eau détecte :',
                 'option_a': 'Le feu',
                 'option_b': 'La tension',
                 'option_c': 'La profondeur d’eau',
                 'option_d': 'Le Bluetooth',
                 'correct': 'C'},
                {'question': 'analogRead() renvoie une valeur comprise entre :',
                 'option_a': '0 et 1023',
                 'option_b': '0 et 255',
                 'option_c': '0 et 5',
                 'option_d': '0 et 1',
                 'correct': 'A'},
                {'question': 'Le capteur HC-SR04 fonctionne avec :',
                 'option_a': 'La lumière UV',
                 'option_b': 'Les ultrasons',
                 'option_c': 'Le Bluetooth',
                 'option_d': 'Le Wi-Fi',
                 'correct': 'B'},
                {'question': 'Pour utiliser le DHT11, il faut généralement :',
                 'option_a': 'Une bibliothèque',
                 'option_b': 'Un amplificateur',
                 'option_c': 'Un convertisseur',
                 'option_d': 'Un shield',
                 'correct': 'A'},
                {'question': 'La fonction pulseIn() est souvent utilisée avec :',
                 'option_a': 'Le capteur ultrason',
                 'option_b': 'La photorésistance',
                 'option_c': 'Le buzzer',
                 'option_d': 'Le relais',
                 'correct': 'A'},
                {'question': 'Un capteur MQ détecte principalement :',
                 'option_a': 'La lumière',
                 'option_b': 'Le gaz/fumée',
                 'option_c': 'Les ultrasons',
                 'option_d': 'Les vibrations',
                 'correct': 'B'},
                {'question': 'Dans un montage voltage divider avec photorésistance, on mesure :',
                 'option_a': 'La tension qui varie avec la lumière',
                 'option_b': 'Le courant direct',
                 'option_c': 'La résistance fixe',
                 'option_d': 'La température',
                 'correct': 'A'},
                {'question': 'Le capteur de niveau d’eau est un capteur :',
                 'option_a': 'Numérique uniquement',
                 'option_b': 'Analogique',
                 'option_c': 'PWM',
                 'option_d': 'I2C',
                 'correct': 'B'}]},
 {'sequence_day': 6,
  'title': 'Challenge 4 — Jour 6 : Mini-projet 2 & Capteurs environnementaux (suite)',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'Dans le projet éclairage automatique, la photorésistance permet de :',
                 'option_a': 'Allumer la LED quand il fait sombre',
                 'option_b': 'Mesurer la température',
                 'option_c': 'Détecter le mouvement',
                 'option_d': 'Contrôler un servo',
                 'correct': 'A'},
                {'question': 'La fonction Serial.begin(9600) sert à :',
                 'option_a': 'Initialiser la communication série',
                 'option_b': 'Attendre 9600 ms',
                 'option_c': 'Configurer une broche',
                 'option_d': 'Lire un capteur',
                 'correct': 'A'},
                {'question': 'Pour calibrer un capteur, on utilise souvent :',
                 'option_a': 'map() ou des seuils (if/else)',
                 'option_b': 'digitalWrite()',
                 'option_c': 'tone()',
                 'option_d': 'attach()',
                 'correct': 'A'},
                {'question': 'Un capteur PIR détecte :',
                 'option_a': 'La lumière',
                 'option_b': 'Le mouvement infrarouge',
                 'option_c': 'Le son',
                 'option_d': 'La distance',
                 'correct': 'B'},
                {'question': 'Le buzzer actif :',
                 'option_a': 'Nécessite un signal PWM',
                 'option_b': 'Émet un son dès qu’il est alimenté',
                 'option_c': 'Ne fonctionne qu’avec une bibliothèque',
                 'option_d': 'Mesure le son',
                 'correct': 'B'},
                {'question': 'La fonction tone(pin, fréquence) permet de :',
                 'option_a': 'Générer un son',
                 'option_b': 'Lire une tension',
                 'option_c': 'Envoyer un signal infrarouge',
                 'option_d': 'Contrôler un moteur',
                 'correct': 'A'},
                {'question': 'Un Tilt Ball Switch est un capteur :',
                 'option_a': 'De vibration / inclinaison',
                 'option_b': 'De lumière',
                 'option_c': 'De gaz',
                 'option_d': 'De distance',
                 'correct': 'A'},
                {'question': 'Le capteur de flamme détecte :',
                 'option_a': 'La lumière infrarouge émise par une flamme',
                 'option_b': 'La température ambiante',
                 'option_c': 'Le monoxyde de carbone',
                 'option_d': 'L’humidité',
                 'correct': 'A'},
                {'question': 'Pour lire plusieurs LEDs avec peu de broches, on utilise souvent :',
                 'option_a': 'Le 74HC595 (shift register)',
                 'option_b': 'Un multiplexeur',
                 'option_c': 'Un amplificateur',
                 'option_d': 'Un DAC',
                 'correct': 'A'},
                {'question': 'Dans le projet photorésistance, on compare généralement la valeur analogique à :',
                 'option_a': 'Un seuil (threshold)',
                 'option_b': '1023',
                 'option_c': '5V',
                 'option_d': '0',
                 'correct': 'A'}]},
 {'sequence_day': 7,
  'title': 'Challenge 5 — Jour 7 : Entrées numériques & Interactions utilisateur / Bibliothèques',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'INPUT_PULLUP sert à :',
                 'option_a': 'Éviter les parasites',
                 'option_b': 'Augmenter le Wi-Fi',
                 'option_c': 'Accélérer Arduino',
                 'option_d': 'Alimenter le capteur',
                 'correct': 'A'},
                {'question': 'Lorsqu’un bouton en INPUT_PULLUP est pressé :',
                 'option_a': 'HIGH',
                 'option_b': 'LOW',
                 'option_c': 'NULL',
                 'option_d': 'TRUE',
                 'correct': 'B'},
                {'question': 'Une entrée numérique lit :',
                 'option_a': '0 ou 1',
                 'option_b': 'Des images',
                 'option_c': 'Du son',
                 'option_d': 'De la température',
                 'correct': 'A'},
                {'question': 'Pour installer une nouvelle bibliothèque :',
                 'option_a': 'Sketch → Inclure une bibliothèque → Ajouter .ZIP Library',
                 'option_b': 'Outils → Compiler',
                 'option_c': 'Fichier → Exemples',
                 'option_d': 'Aide → Mise à jour',
                 'correct': 'A'},
                {'question': 'La fonction debounce sert à :',
                 'option_a': 'Éviter les rebonds d’un bouton',
                 'option_b': 'Augmenter la luminosité',
                 'option_c': 'Mesurer le temps',
                 'option_d': 'Envoyer des données',
                 'correct': 'A'},
                {'question': 'Un clavier matriciel 4x4 nécessite :',
                 'option_a': 'Beaucoup de broches ou une bonne gestion des lignes/colonnes',
                 'option_b': 'Une seule broche analogique',
                 'option_c': 'Le bus I2C uniquement',
                 'option_d': 'Aucune bibliothèque',
                 'correct': 'A'},
                {'question': 'La fonction millis() permet de :',
                 'option_a': 'Compter le temps sans bloquer le programme (non-bloquant)',
                 'option_b': 'Attendre comme delay()',
                 'option_c': 'Mesurer la distance',
                 'option_d': 'Contrôler un servo',
                 'correct': 'A'},
                {'question': 'Le module RFID utilise généralement le protocole :',
                 'option_a': 'SPI',
                 'option_b': 'I2C',
                 'option_c': 'UART',
                 'option_d': 'PWM',
                 'correct': 'A'},
                {'question': 'Pour utiliser un servo-moteur, on utilise la fonction :',
                 'option_a': 'servo.write(angle)',
                 'option_b': 'analogWrite()',
                 'option_c': 'digitalRead()',
                 'option_d': 'tone()',
                 'correct': 'A'},
                {'question': 'Ajouter #include <LibraryName.h> permet de :',
                 'option_a': 'Utiliser les fonctions de la bibliothèque',
                 'option_b': 'Compiler plus vite',
                 'option_c': 'Téléverser le code',
                 'option_d': 'Ouvrir le moniteur série',
                 'correct': 'A'}]},
 {'sequence_day': 8,
  'title': 'Challenge 6 — Jour 8 : Actionneurs et modules de contrôle',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'Un relais permet de contrôler :',
                 'option_a': 'Des charges haute tension / fort courant',
                 'option_b': 'Des signaux PWM faibles',
                 'option_c': 'Des capteurs analogiques',
                 'option_d': 'Des écrans LCD',
                 'correct': 'A'},
                {'question': 'Un servomoteur permet un mouvement :',
                 'option_a': 'De 0 à 180 degrés généralement',
                 'option_b': 'En rotation continue',
                 'option_c': 'À très haute vitesse',
                 'option_d': 'Linéaire uniquement',
                 'correct': 'A'},
                {'question': 'Le CI 74HC595 est un :',
                 'option_a': 'Registre à décalage (shift register)',
                 'option_b': 'Capteur de température',
                 'option_c': 'Convertisseur analogique',
                 'option_d': 'Amplificateur',
                 'correct': 'A'},
                {'question': 'La fonction attach() pour un servo est utilisée dans :',
                 'option_a': 'setup()',
                 'option_b': 'loop() uniquement',
                 'option_c': 'main()',
                 'option_d': 'Serial.begin()',
                 'correct': 'A'},
                {'question': 'Un moteur DC classique nécessite :',
                 'option_a': 'Un pont en H ou un driver (L298N, etc.)',
                 'option_b': 'Un signal PWM direct sur Arduino',
                 'option_c': 'Une bibliothèque DHT',
                 'option_d': 'Le bus I2C',
                 'correct': 'A'},
                {'question': 'Le capteur ultrason HC-SR04 renvoie la distance en calculant :',
                 'option_a': 'Le temps d’écho',
                 'option_b': 'La résistance',
                 'option_c': 'La tension',
                 'option_d': 'L’humidité',
                 'correct': 'A'},
                {'question': 'Un buzzer passif nécessite :',
                 'option_a': 'Un signal PWM ou tone()',
                 'option_b': 'Une alimentation continue',
                 'option_c': 'Aucune résistance',
                 'option_d': 'Le moniteur série',
                 'correct': 'A'},
                {'question': 'Le module relais a généralement un optocoupleur pour :',
                 'option_a': 'Isoler galvaniquement Arduino',
                 'option_b': 'Augmenter la luminosité',
                 'option_c': 'Mesurer le courant',
                 'option_d': 'Envoyer des données',
                 'correct': 'A'},
                {'question': 'Pour contrôler plusieurs actionneurs, on privilégie :',
                 'option_a': 'Les multiplexeurs et registres à décalage',
                 'option_b': 'Toutes les broches analogiques',
                 'option_c': 'Le WiFi uniquement',
                 'option_d': 'Le Bluetooth',
                 'correct': 'A'},
                {'question': 'La commande servo.write(90) positionne le servo :',
                 'option_a': 'Au milieu (90°)',
                 'option_b': 'À 0°',
                 'option_c': 'À 180°',
                 'option_d': 'En rotation continue',
                 'correct': 'A'}]},
 {'sequence_day': 9,
  'title': 'Challenge 7 — Jour 9 : Affichage et communication',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'L’écran LCD 16x2 communique souvent via :',
                 'option_a': 'Le bus I2C (avec adaptateur) ou en parallèle',
                 'option_b': 'Le SPI uniquement',
                 'option_c': 'Le PWM',
                 'option_d': 'Les ultrasons',
                 'correct': 'A'},
                {'question': 'La fonction lcd.print() nécessite :',
                 'option_a': 'D’avoir initialisé l’écran avec LiquidCrystal',
                 'option_b': 'Le moniteur série',
                 'option_c': 'Une photorésistance',
                 'option_d': 'Un servo',
                 'correct': 'A'},
                {'question': 'Le module RFID permet :',
                 'option_a': 'L’identification sans contact',
                 'option_b': 'La mesure de distance',
                 'option_c': 'Le contrôle de moteur',
                 'option_d': 'L’affichage 7 segments',
                 'correct': 'A'},
                {'question': 'Un afficheur 7 segments permet d’afficher :',
                 'option_a': 'Des chiffres de 0 à 9',
                 'option_b': 'Du texte complet',
                 'option_c': 'Des images',
                 'option_d': 'Des graphiques',
                 'correct': 'A'},
                {'question': 'La bibliothèque LiquidCrystal permet de contrôler :',
                 'option_a': 'Un écran LCD',
                 'option_b': 'Un servo',
                 'option_c': 'Un capteur DHT',
                 'option_d': 'Un buzzer',
                 'correct': 'A'},
                {'question': 'Pour afficher un message personnalisé sur LCD, on utilise souvent :',
                 'option_a': 'lcd.setCursor() et lcd.print()',
                 'option_b': 'Serial.print()',
                 'option_c': 'analogWrite()',
                 'option_d': 'tone()',
                 'correct': 'A'},
                {'question': 'Le protocole I2C permet :',
                 'option_a': 'De connecter plusieurs périphériques avec seulement 2 fils',
                 'option_b': 'Une communication très rapide',
                 'option_c': 'Le contrôle de moteurs puissants',
                 'option_d': 'La mesure analogique',
                 'correct': 'A'},
                {'question': 'Un afficheur 7 segments à cathode commune :',
                 'option_a': 'Relie toutes les cathodes ensemble',
                 'option_b': 'Toutes les anodes ensemble',
                 'option_c': 'Ne nécessite pas de résistance',
                 'option_d': 'Fonctionne uniquement en I2C',
                 'correct': 'A'},
                {'question': 'La télécommande IR utilise :',
                 'option_a': 'Le récepteur infrarouge (VS1838)',
                 'option_b': 'Les ultrasons',
                 'option_c': 'Le Bluetooth',
                 'option_d': 'Le WiFi',
                 'correct': 'A'},
                {'question': 'Pour faire défiler du texte sur un LCD, on utilise généralement :',
                 'option_a': 'Une boucle avec lcd.scrollDisplayLeft()',
                 'option_b': 'delay() uniquement',
                 'option_c': 'analogRead()',
                 'option_d': 'digitalWrite()',
                 'correct': 'A'}]},
 {'sequence_day': 10,
  'title': 'Challenge 8 — Jour 10 : Mini-projet 4 (LCD) & Microcontrôleurs alternatifs',
  'description': 'Type : QCM (20 pts)',
  'questions': [{'question': 'Le mini-projet 4 consiste à :',
                 'option_a': 'Afficher un message personnalisé sur un écran LCD',
                 'option_b': 'Faire un feu tricolore',
                 'option_c': 'Contrôler un servo avec un bouton',
                 'option_d': 'Mesurer la température',
                 'correct': 'A'},
                {'question': 'L’ESP32 est connu pour avoir :',
                 'option_a': 'WiFi et Bluetooth intégrés',
                 'option_b': 'Moins de broches que l’Uno',
                 'option_c': 'Pas de PWM',
                 'option_d': 'Uniquement 5V',
                 'correct': 'A'},
                {'question': 'La carte Arduino Nano est :',
                 'option_a': 'Plus petite que l’Uno mais compatible',
                 'option_b': 'Plus puissante que l’ESP32',
                 'option_c': 'Sans microcontrôleur AVR',
                 'option_d': 'Uniquement pour l’IoT',
                 'correct': 'A'},
                {'question': 'Pour un projet final, on recommande souvent :',
                 'option_a': 'De combiner plusieurs composants appris',
                 'option_b': 'D’utiliser uniquement le Blink',
                 'option_c': 'De ne pas utiliser de bibliothèque',
                 'option_d': 'D’éviter le moniteur série',
                 'correct': 'A'},
                {'question': 'Un avantage de l’ESP32 par rapport à l’Uno :',
                 'option_a': 'Plus de mémoire et connectivité sans fil',
                 'option_b': 'Moins cher',
                 'option_c': 'Plus facile pour les débutants',
                 'option_d': 'Moins de broches PWM',
                 'correct': 'A'},
                {'question': 'Dans un projet LCD, lcd.begin(16, 2) permet de :',
                 'option_a': 'Initialiser un écran 16 colonnes x 2 lignes',
                 'option_b': 'Afficher 16 caractères',
                 'option_c': 'Changer la luminosité',
                 'option_d': 'Lire un bouton',
                 'correct': 'A'},
                {'question': 'Le bus SPI est souvent utilisé pour :',
                 'option_a': 'Les afficheurs, RFID, SD cards',
                 'option_b': 'Les capteurs de température simples',
                 'option_c': 'Les boutons poussoirs',
                 'option_d': 'Les LEDs simples',
                 'correct': 'A'},
                {'question': 'Un bon projet de fin doit généralement contenir :',
                 'option_a': 'Capteur + traitement + actionneur + affichage',
                 'option_b': 'Uniquement des LEDs',
                 'option_c': 'Pas de code',
                 'option_d': 'Que du Python',
                 'correct': 'A'},
                {'question': 'La fonction String() ou sprintf() sert à :',
                 'option_a': 'Formater du texte pour l’affichage',
                 'option_b': 'Lire un capteur analogique',
                 'option_c': 'Contrôler un relais',
                 'option_d': 'Générer un son',
                 'correct': 'A'},
                {'question': 'Lors de la présentation d’un projet, il est important de :',
                 'option_a': 'Expliquer le câblage, le code et le fonctionnement',
                 'option_b': 'Seulement montrer le montage',
                 'option_c': 'Ne pas commenter le code',
                 'option_d': 'Utiliser uniquement le moniteur série',
                 'correct': 'A'}]}]

ANSWER_MARKERS = ("\u2705", "\u2714", "\u2713", "\u2611", "?")
OPTION_FIELDS = (
    ("A", "option_a"),
    ("B", "option_b"),
    ("C", "option_c"),
    ("D", "option_d"),
)
VALID_CORRECT_OPTIONS = {"A", "B", "C", "D"}


def option_has_answer_marker(option_value):
    text = str(option_value or "")
    return any(marker in text for marker in ANSWER_MARKERS)


def strip_answer_markers(option_value):
    cleaned = str(option_value or "")
    for marker in ANSWER_MARKERS:
        cleaned = cleaned.replace(marker, "")
    return " ".join(cleaned.split())


def normalize_question_payload(question_data):
    normalized = dict(question_data or {})
    marked_options = []
    for letter, field_name in OPTION_FIELDS:
        original_value = normalized.get(field_name, "")
        if option_has_answer_marker(original_value):
            marked_options.append(letter)
        normalized[field_name] = strip_answer_markers(original_value)

    provided_correct = str(normalized.get("correct") or "").strip().upper()
    if len(marked_options) == 1:
        normalized["correct"] = marked_options[0]
    elif provided_correct in VALID_CORRECT_OPTIONS:
        normalized["correct"] = provided_correct
    else:
        normalized["correct"] = "A"
    return normalized
